# Generated by Django 5.2.1 on 2026-03-26 10:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Directorate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Equipment Category',
                'verbose_name_plural': 'Equipment Categories',
                'db_table': 'equipment_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Equipment Status',
                'verbose_name_plural': 'Equipment Statuses',
                'db_table': 'equipment_status',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('directorate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='equipment.directorate')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DPUOffice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name',), name='unique_dpuoffice_name')],
            },
        ),
        migrations.CreateModel(
            name='DPU',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('dpu_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dpuhq_office', to='equipment.dpuoffice')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dpus', to='equipment.region')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brands', to='equipment.equipmentcategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offices', to='equipment.department')),
                ('dpu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offices', to='equipment.dpu')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offices', to='equipment.region')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RegionOffice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name',), name='unique_regionoffice_name')],
            },
        ),
        migrations.AddField(
            model_name='region',
            name='region_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regionhq_office', to='equipment.regionoffice'),
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('dpu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stations', to='equipment.dpu')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('registration_intent', models.CharField(choices=[('Stock', 'Add to Stock (keep in IT store)'), ('Deployment', 'Deploy Immediately (issue to a unit/person)')], default='Stock', help_text='Stock → item is added to the IT store immediately. Deployment → item is issued to a location/person immediately.', max_length=20)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(50)])),
                ('marking_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('deployment_date', models.DateField(blank=True, null=True)),
                ('warranty_expiration', models.DateField(blank=True, null=True)),
                ('CPU', models.CharField(blank=True, max_length=50, null=True)),
                ('ram_size', models.CharField(blank=True, max_length=10, null=True)),
                ('storage_size', models.CharField(blank=True, max_length=10, null=True)),
                ('GPU', models.CharField(blank=True, max_length=50, null=True)),
                ('operating_system', models.CharField(blank=True, max_length=50, null=True)),
                ('ram_slots', models.IntegerField(blank=True, null=True)),
                ('storage_slots', models.IntegerField(blank=True, null=True)),
                ('storage_type', models.CharField(blank=True, max_length=100, null=True)),
                ('screen_size', models.CharField(blank=True, max_length=100, null=True)),
                ('printer_type', models.CharField(blank=True, max_length=100, null=True)),
                ('network_type', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone_type', models.CharField(blank=True, max_length=100, null=True)),
                ('exstorage_type', models.CharField(blank=True, max_length=100, null=True)),
                ('peripheral_type', models.CharField(blank=True, max_length=100, null=True)),
                ('ups', models.CharField(blank=True, max_length=100, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='equipment.brand')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_equipment', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='equipment.department')),
                ('directorate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='equipment.directorate')),
                ('dpu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='equipment.dpu')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_equipment', to=settings.AUTH_USER_MODEL)),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_types', to='equipment.equipmentcategory')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='equipment.equipmentstatus')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='equipment.office')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='equipment.region')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='equipment.station')),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipment',
                'db_table': 'equipment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storage_location', models.CharField(blank=True, help_text='Logistics or IT Tech Support.', max_length=100, null=True)),
                ('date_added', models.DateField(default=django.utils.timezone.now, help_text='Date this item was placed into stock.')),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_additions', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='stock', to='equipment.equipment')),
            ],
            options={
                'verbose_name': 'Stock Item',
                'verbose_name_plural': 'Stock Items',
                'db_table': 'stock',
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name',), name='unique_unit_name')],
            },
        ),
        migrations.CreateModel(
            name='Lending',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Active', 'Active — currently out'), ('Returned', 'Returned to stock')], default='Active', max_length=10)),
                ('borrower_name', models.CharField(help_text='Person borrowing the equipment.', max_length=100)),
                ('phone_number', models.CharField(help_text="Borrower's phone number", max_length=20)),
                ('purpose', models.TextField(help_text='Reason for borrowing.')),
                ('issued_date', models.DateField(default=django.utils.timezone.now)),
                ('returned_date', models.DateField(blank=True, null=True)),
                ('returned_by', models.CharField(blank=True, max_length=100, null=True)),
                ('condition_on_return', models.CharField(choices=[('New', 'New'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor'), ('Damaged', 'Damaged'), ('Under Repair', 'Under Repair')], default='Good', max_length=100)),
                ('return_comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dpu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dpu_borrower', to='equipment.dpu')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lendings', to='equipment.equipment')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_lendings', to=settings.AUTH_USER_MODEL)),
                ('return_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_lending_returns', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='region_borrower', to='equipment.region')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='station_borrower', to='equipment.station')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unit_borrower', to='equipment.unit')),
            ],
            options={
                'verbose_name': 'Lending',
                'verbose_name_plural': 'Lendings',
                'db_table': 'lending',
                'ordering': ['-issued_date'],
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='equipment.unit'),
        ),
        migrations.AddField(
            model_name='directorate',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='directorates', to='equipment.unit'),
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Active', 'Active — currently deployed')], default='Active', max_length=10)),
                ('issued_to_user', models.CharField(blank=True, help_text='Individual who received the equipment.', max_length=100, null=True)),
                ('issued_date', models.DateField(default=django.utils.timezone.now)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_deployments', to=settings.AUTH_USER_MODEL)),
                ('issued_to_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='equipment.department')),
                ('issued_to_directorate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='equipment.directorate')),
                ('issued_to_dpu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='equipment.dpu')),
                ('issued_to_dpu_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='equipment.dpuoffice')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='equipment.equipment')),
                ('issued_to_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='equipment.office')),
                ('issued_to_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='equipment.region')),
                ('issued_to_region_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='equipment.regionoffice')),
                ('issued_to_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='equipment.station')),
                ('issued_to_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='equipment.unit')),
            ],
            options={
                'verbose_name': 'Deployment',
                'verbose_name_plural': 'Deployments',
                'db_table': 'deployment',
                'ordering': ['-issued_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(condition=models.Q(('directorate__isnull', False)), fields=('name', 'directorate'), name='unique_department_per_directorate'),
        ),
        migrations.AddConstraint(
            model_name='brand',
            constraint=models.UniqueConstraint(fields=('name', 'category'), name='unique_brand_per_category'),
        ),
        migrations.AddConstraint(
            model_name='office',
            constraint=models.UniqueConstraint(condition=models.Q(('department__isnull', False)), fields=('name', 'department'), name='unique_office_per_department'),
        ),
        migrations.AddConstraint(
            model_name='dpu',
            constraint=models.UniqueConstraint(fields=('name', 'region'), name='unique_dpu_per_region'),
        ),
        migrations.AddConstraint(
            model_name='region',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_region_name'),
        ),
        migrations.AddConstraint(
            model_name='station',
            constraint=models.UniqueConstraint(fields=('name', 'dpu'), name='unique_station_per_dpu'),
        ),
        migrations.AddConstraint(
            model_name='directorate',
            constraint=models.UniqueConstraint(condition=models.Q(('unit__isnull', False)), fields=('name', 'unit'), name='unique_directorate_per_unit'),
        ),
    ]
