# Generated by Django 6.0.2 on 2026-03-12 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_fix_deployment_dpu_office_fk_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='marking_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(50)]),
        ),
    ]
